os:
  - linux
  - osx
  # - windows - travis isn't windows ready yet; tests fail for meaningless reasons

language: node_js
node_js:
  - 12
  - 10
  - 8

install:
  - yarn install --frozen-lockfile
  - yarn build
  - yarn add $WEBPACK $TSLOADER $VUELOADER -D

script:
  - yarn test

env:
  - WEBPACK=webpack@^5.0.0-alpha.5 TSLOADER=ts-loader@^5.0.0 VUELOADER=vue-loader@^15.2.4
  - WEBPACK=webpack@^4.0.0 TSLOADER=ts-loader@^5.0.0 VUELOADER=vue-loader@^15.2.4
  - WEBPACK=webpack@^3.10.0 TSLOADER=ts-loader@^3.4.0 VUELOADER=vue-loader@^13.5.0
  - WEBPACK=webpack@^2.7.0 TSLOADER=ts-loader@^3.4.0 VUELOADER=vue-loader@^13.5.0

jobs:
  include:
    - stage: release
      node_js: 10
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn exec semantic-release
        on:
          all_branches: true
